spring:
  datasource:
    url: jdbc:postgresql://dpg-cmv7cdn109ks73b9ga60-a.oregon-postgres.render.com:5432/projectdb_f9w1
    username: fejjsan
    password: H5ZITOBQ4oo5yeupMCIkNsBUxHVZt63u
  config:
    active:
      on-profile: production