server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://dpg-cmv7cdn109ks73b9ga60-a/projectdb_f9w1
    username: fejjsan
    password: H5ZITOBQ4oo5yeupMCIkNsBUxHVZt63u
  config:
    active:
      on-profile: production